// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv1gfukgZK2m4dAOldw_iH9z_muWfjYpQ',
    appId: '1:906955156808:web:1630de5fc099a68247d77d',
    messagingSenderId: '906955156808',
    projectId: 'securetrace-2025',
    authDomain: 'trace-2025.firebaseapp.com',
    storageBucket: 'securetrace-2025.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxvjaP0tqoQdqvTm3dYg_hEA_8w-cfBaA',
    appId: '1:906955156808:android:0bc9d2da4a8e45a247d77d',
    messagingSenderId: '906955156808',
    projectId: 'securetrace-2025',
    storageBucket: 'securetrace-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3rFpv0L3-eS6eFpg47OaiTVK304K9Dqs',
    appId: '1:906955156808:ios:c67b776fd83228e247d77d',
    messagingSenderId: '906955156808',
    projectId: 'securetrace-2025',
    storageBucket: 'securetrace-2025.firebasestorage.app',
    iosBundleId: 'com.example.secureTrace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3rFpv0L3-eS6eFpg47OaiTVK304K9Dqs',
    appId: '1:906955156808:ios:c67b776fd83228e247d77d',
    messagingSenderId: '906955156808',
    projectId: 'securetrace-2025',
    storageBucket: 'securetrace-2025.firebasestorage.app',
    iosBundleId: 'com.example.secureTrace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCv1gfukgZK2m4dAOldw_iH9z_muWfjYpQ',
    appId: '1:906955156808:web:c7661926096f5e6347d77d',
    messagingSenderId: '906955156808',
    projectId: 'securetrace-2025',
    authDomain: 'trace-2025.firebaseapp.com',
    storageBucket: 'securetrace-2025.firebasestorage.app',
  );
}
